In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [12]:
d=pd.read_csv(r'D:\DA\SUV Predictions data.csv')

In [13]:
d

No   User ID Gender   Age  Salary  Purchased
0   0  15624510       M   19   19000          0
1   1  15810944       M   26   20000          0
2   2  15668575       F   27   43000          0
3   3  15603246       F   19   57000          0
4   4  15804002       M   27   76000          0
5   5  15728773       M   27   58000          0
6   6  15598044       F   32   84000          0
7   7  15694829       F   25  150000          1
8   8  15600575       M   25   33000          0
9   9  15727311       F   35   65000          0

In [21]:
d.isnull().sum()

No           0
User ID      0
Gender       0
Age          0
Salary       0
Purchased    0
dtype: int64

In [15]:
d.head(5)

No   User ID Gender   Age  Salary  Purchased
0   0  15624510       M   19   19000          0
1   1  15810944       M   26   20000          0
2   2  15668575       F   27   43000          0
3   3  15603246       F   19   57000          0
4   4  15804002       M   27   76000          0

In [35]:
d.drop('No',axis=1,inplace=True)

In [36]:
d

User ID Gender   Age  Salary  Purchased
0  15624510       M   19   19000          0
1  15810944       M   26   20000          0
2  15668575       F   27   43000          0
3  15603246       F   19   57000          0
4  15804002       M   27   76000          0
5  15728773       M   27   58000          0
6  15598044       F   32   84000          0
7  15694829       F   25  150000          1
8  15600575       M   25   33000          0
9  15727311       F   35   65000          0

In [37]:
x=d.iloc[:,[2,3]].values
y=d.iloc[:,4].values

In [38]:
x

array([[    19,  19000],
       [    26,  20000],
       [    27,  43000],
       [    19,  57000],
       [    27,  76000],
       [    27,  58000],
       [    32,  84000],
       [    25, 150000],
       [    25,  33000],
       [    35,  65000]], dtype=int64)

In [39]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [42]:
x_train

array([[    32,  84000],
       [    27,  76000],
       [    19,  19000],
       [    19,  57000],
       [    26,  20000],
       [    25, 150000],
       [    25,  33000],
       [    27,  58000]], dtype=int64)

In [43]:
x_test

array([[   27, 43000],
       [   35, 65000]], dtype=int64)

In [44]:
y_train

array([0, 0, 0, 0, 0, 1, 0, 0], dtype=int64)

In [45]:
y_test

array([0, 0], dtype=int64)

In [46]:
x_train.shape

(8, 2)

In [47]:
y_train.shape

(8,)

In [48]:
x_test.shape

(2, 2)

In [49]:
y_test.shape

(2,)

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
c=LogisticRegression()
c.fit(x_train,y_train)

LogisticRegression()

In [52]:
y_pred=c.predict(x_test)

In [53]:
y_pred

array([0, 0], dtype=int64)

In [59]:
from sklearn.metrics import confusion_matrix

In [60]:
c1=confusion_matrix(y_test,y_pred)

In [61]:
c1

array([[2]], dtype=int64)

In [62]:
pd.crosstab(y_test,y_pred)

col_0  0
row_0   
0      2

In [54]:
from sklearn.metrics import accuracy_score

In [56]:
accuracy_score(y_test,y_pred)*100

100.0